%% Surface plots of performance vs. Ld and area ratio
clear; clc;

%% ===================== USER SETTINGS ====================================
% Number of discrete colors per variable (10, 20, ...)
nColors_eta = 10;   % Peak flow reduction
nColors_dt  = 10;   % Time-to-peak delay
nColors_det = 10;   % Detention time

% Colorbar limits (min, max) for each variable
eta_clim = [ 0 40];   % [%]       Peak flow reduction
dt_clim  = [ 0 80];   % [min]     Time-to-peak delay
det_clim = [10 40];   % [h]       Detention time

% Number of ticks for Ld axis (smooth, not every tested value)
nTicks_Ld = 5;
% ========================================================================

% --- LaTeX + font defaults ---
set(0,'DefaultTextInterpreter','latex');
set(0,'DefaultAxesTickLabelInterpreter','latex');
set(0,'DefaultLegendInterpreter','latex');
set(0,'DefaultAxesFontSize',14);
set(0,'DefaultTextFontSize',14);

% --- Load database generated by DRAIN-LID script ---
S = load('DRAIN_LID_database_single.mat', 'Metrics');
Metrics = S.Metrics;

% --- Extract unique design variables (Ld, area_ratio) ---
Ld_vals = sort(unique([Metrics.Ld_m]).');          % [m]
AR_vals = sort(unique([Metrics.area_ratio]).');    % [-] (fraction)

nLd = numel(Ld_vals);
nAR = numel(AR_vals);

% --- Preallocate surfaces ---
Z_eta_p   = nan(nLd, nAR);  % peak flow reduction [%]
Z_dt_peak = nan(nLd, nAR);  % time-to-peak delay [min]
Z_det_hr  = nan(nLd, nAR);  % detention time [h]

% --- Fill surfaces from Metrics ---
for iLd = 1:nLd
    for jAR = 1:nAR
        idx = find( abs([Metrics.Ld_m]       - Ld_vals(iLd))  < 1e-6 & ...
                    abs([Metrics.area_ratio] - AR_vals(jAR)) < 1e-6, ...
                    1, 'first');
        if ~isempty(idx)
            Z_eta_p(iLd, jAR)   = Metrics(idx).eta_p_pct;        % [%]
            Z_dt_peak(iLd, jAR) = Metrics(idx).Delta_tp_min;     % [min]
            Z_det_hr(iLd, jAR)  = Metrics(idx).DetTime_min/60;   % [h]
        end
    end
end

% --- Meshgrid for plotting (x in %) ---
[AR_grid, Ld_grid] = meshgrid(AR_vals, Ld_vals);
AR_grid_pct = AR_grid * 100;

% X ticks (use tested area ratios, but expressed in %)
xTicks      = AR_vals * 100;
xTickLabels = arrayfun(@(v) sprintf('%.0f', v), xTicks, 'UniformOutput', false);

% Y ticks (smooth, not every tested Ld)
Ld_min  = min(Ld_vals);
Ld_max  = max(Ld_vals);
yTicks  = linspace(Ld_min, Ld_max, nTicks_Ld);
yTickLabels = arrayfun(@(v) sprintf('%.1f', v), yTicks, 'UniformOutput', false);

% --- Figure setup: 1x3, full A4 width (landscape-like) ---
fig = figure('Units','centimeters', ...
             'Position',[1 1 29.7 10], ...
             'PaperUnits','centimeters', ...
             'PaperSize',[29.7 21], ...
             'PaperPosition',[0 0 29.7 10]);

%% 1) Peak flow reduction
ax1 = subplot(1,3,1);

surf(AR_grid_pct, Ld_grid, Z_eta_p);
view(2); shading interp;
xlabel('Area ratio [\%]');
ylabel('$L_d\;[\mathrm{m}]$');
title('Peak flow reduction');

set(ax1, 'TickDir','out', ...
         'Box','on', ...
         'Layer','top', ...
         'FontSize',14, ...
         'LineWidth',1.5, ...
         'XTick', xTicks, ...
         'XTickLabel', xTickLabels, ...
         'YTick', yTicks, ...
         'YTickLabel', yTickLabels);
grid(ax1, 'off');

% Color limits and discrete colormap
caxis(ax1, eta_clim);
colormap(ax1, parula(nColors_eta));

cb1 = colorbar(ax1);
cb1.Label.Interpreter = 'latex';
cb1.Label.String      = '$\eta_p\;[\%]$';
cb1.LineWidth         = 1.5;
cb1.TickDirection     = 'in';
cb1.TickLength        = 0.025;
cb1.FontSize          = 14;

% Integer ticks matching number of colors (rounded)
eta_ticks = round(linspace(eta_clim(1), eta_clim(2), nColors_eta+1));
cb1.Ticks = unique(eta_ticks);

%% 2) Time-to-peak delay
ax2 = subplot(1,3,2);

surf(AR_grid_pct, Ld_grid, Z_dt_peak);
view(2); shading interp;
xlabel('Area ratio [\%]');
ylabel('$L_d\;[\mathrm{m}]$');
title('Time-to-peak delay');

set(ax2, 'TickDir','out', ...
         'Box','on', ...
         'Layer','top', ...
         'FontSize',14, ...
         'LineWidth',1.5, ...
         'XTick', xTicks, ...
         'XTickLabel', xTickLabels, ...
         'YTick', yTicks, ...
         'YTickLabel', yTickLabels);
grid(ax2, 'off');

caxis(ax2, dt_clim);
colormap(ax2, hot(nColors_dt));

cb2 = colorbar(ax2);
cb2.Label.Interpreter = 'latex';
cb2.Label.String      = '$\Delta t_p\;[\mathrm{min}]$';
cb2.LineWidth         = 1.5;
cb2.TickDirection     = 'in';
cb2.TickLength        = 0.025;
cb2.FontSize          = 14;

dt_ticks = round(linspace(dt_clim(1), dt_clim(2), nColors_dt + 1));
cb2.Ticks = unique(dt_ticks);

%% 3) Detention time (hours)
ax3 = subplot(1,3,3);

surf(AR_grid_pct, Ld_grid, Z_det_hr);
view(2); shading interp;
xlabel('Area ratio [\%]');
ylabel('$L_d\;[\mathrm{m}]$');
title('Detention time');

set(ax3, 'TickDir','out', ...
         'Box','on', ...
         'Layer','top', ...
         'FontSize',14, ...
         'LineWidth',1.5, ...
         'XTick', xTicks, ...
         'XTickLabel', xTickLabels, ...
         'YTick', yTicks, ...
         'YTickLabel', yTickLabels);
grid(ax3, 'off');

caxis(ax3, det_clim);
colormap(ax3, winter(nColors_det));

cb3 = colorbar(ax3);
cb3.Label.Interpreter = 'latex';
cb3.Label.String      = '$t_d\;[\mathrm{h}]$';
cb3.LineWidth         = 1.5;
cb3.TickDirection     = 'in';
cb3.TickLength        = 0.025;
cb3.FontSize          = 14;

det_ticks = round(linspace(det_clim(1), det_clim(2), nColors_det + 1));
cb3.Ticks = unique(det_ticks);

drawnow;
